import type { Urgency } from "./schemas";

/**
 * Static UK pathway definitions.
 *
 * These are NOT generated by an LLM. The action list and the safety-netting advice for a
 * 999-level presentation are the highest-stakes text in the entire product, and they are
 * identical for every patient at that level. There is no upside to letting a model
 * paraphrase them and a very obvious downside.
 *
 * The LLM's job is limited to the empathetic bridging prose around these.
 */
export interface Pathway {
  urgency: Urgency;
  headline: string;
  actions: string[];
  safetyNetting: string[];
  /** Drives UI colour/severity treatment. */
  severity: "critical" | "urgent" | "moderate" | "routine" | "low";
}

export const PATHWAYS: Record<Urgency, Pathway> = {
  EMERGENCY_999: {
    urgency: "EMERGENCY_999",
    headline: "This is a medical emergency. Call 999 now.",
    actions: [
      "Call 999 immediately.",
      "Stay where you are and do not drive yourself.",
      "Unlock your front door if you can, so paramedics can reach you.",
      "If you have been prescribed a GTN spray or an adrenaline auto-injector, use it as directed.",
    ],
    safetyNetting: [
      "If you become drowsy, confused, or struggle to stay awake, tell the 999 call handler.",
      "If someone is with you, ask them to stay with you until help arrives.",
    ],
    severity: "critical",
  },
  A_AND_E: {
    urgency: "A_AND_E",
    headline: "You need to be seen in A&E today.",
    actions: [
      "Go to your nearest A&E department now.",
      "Ask someone to take you, or call 111 if you cannot get there safely.",
      "Bring a list of your current medications.",
    ],
    safetyNetting: [
      "If your symptoms get suddenly worse on the way, call 999.",
      "Do not wait to see if it settles on its own.",
    ],
    severity: "critical",
  },
  NHS_111: {
    urgency: "NHS_111",
    headline: "Contact NHS 111 today for urgent advice.",
    actions: [
      "Call 111, or go to 111.nhs.uk.",
      "They are open 24 hours a day and can arrange an urgent appointment if you need one.",
      "Have your symptoms and medications to hand.",
    ],
    safetyNetting: [
      "Call 999 instead if you develop chest pain, severe breathlessness, confusion, or you cannot stay awake.",
    ],
    severity: "urgent",
  },
  GP_URGENT: {
    urgency: "GP_URGENT",
    headline: "Contact your GP practice today.",
    actions: [
      "Ring your GP practice as soon as it opens and ask for an urgent, same-day appointment.",
      "Tell reception exactly which symptoms you have — it affects how quickly you are seen.",
      "If the practice is closed, call NHS 111 instead.",
    ],
    safetyNetting: [
      "If you cannot get an appointment today, call 111 rather than waiting.",
      "Call 999 if your symptoms become severe.",
    ],
    severity: "moderate",
  },
  GP_ROUTINE: {
    urgency: "GP_ROUTINE",
    headline: "Book a routine GP appointment.",
    actions: [
      "Book an appointment with your GP in the next week or two.",
      "Keep a short note of when your symptoms happen and what makes them better or worse.",
    ],
    safetyNetting: [
      "Bring the appointment forward if your symptoms get worse, or if new symptoms appear.",
    ],
    severity: "routine",
  },
  PHARMACIST: {
    urgency: "PHARMACIST",
    headline: "A pharmacist can help with this.",
    actions: [
      "Visit any community pharmacy — no appointment needed.",
      "Under Pharmacy First, pharmacists can now treat several common conditions directly.",
      "Tell them what medications you already take.",
    ],
    safetyNetting: [
      "See your GP if it has not improved within a week, or sooner if it worsens.",
    ],
    severity: "low",
  },
  SELF_CARE: {
    urgency: "SELF_CARE",
    headline: "This can usually be managed at home.",
    actions: ["Rest, keep hydrated, and monitor how you feel."],
    safetyNetting: [
      "Contact your GP or NHS 111 if things get worse, do not improve as expected, or you become worried.",
    ],
    severity: "low",
  },
};
